import type { NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/Card'

import css from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={css.host}>
      <Head>
        <title>NextJS Hacker News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={css.title}>NextJS Hacker news</h1>
      <main className={css.main}>
        <Card
          by="theafh"
          score={773}
          time={1658759093}
          title="Two weeks in, the Webb Space Telescope is reshaping astronomy"
          url="https://www.quantamagazine.org/two-weeks-in-the-webb-space-telescope-is-reshaping-astronomy-20220725/"
        />
        <Card
          by="theafh"
          score={773}
          time={1658759093}
          title="Two weeks in, the Webb Space Telescope is reshaping astronomy"
          url="https://www.quantamagazine.org/two-weeks-in-the-webb-space-telescope-is-reshaping-astronomy-20220725/"
        />
        <Card
          by="theafh"
          score={773}
          time={1658759093}
          title="Two weeks in, the Webb Space Telescope is reshaping astronomy"
          url="https://www.quantamagazine.org/two-weeks-in-the-webb-space-telescope-is-reshaping-astronomy-20220725/"
        />
      </main>
    </div>
  )
}

export default Home
